### ISSUE TITLE
Worker not deploying

### ISSUE THREAD

**Issue by morph2k** [willswire/unifi-ddns#81]
I had to deploy a test worker just to get the Worker account ID, but using the Hello World test worker gave me an ID, so that part should be done. Then I set up an API with the Edit Cloudflare Workers API template and added the Zone:DNS:Edit permission. 

I forked the repo here on Github and enabled Actions for the repo. 

When I finish the deployment, It fails with an Error. I can't find a way to get more details about what the error is though. I'm not really sure what's going wrong here. 

This is all that it gives me. The Actions tab for the repo is empty when I go there. 

![image](https://github.com/user-attachments/assets/78a8c166-66d8-42eb-a949-2faf84187187)

**Comment by 5454mono** [comment]
I had the same issues. I made multiple changes between attempts, one of them being the deployment of the test/Hello World worker, which did seem an essential one. In order to get things to reset I started over in an "incognito" window each time.

The other thing I did differently during my final/successful attempt, was manually trigger the "Deploy" action in GitHub. Going from memory (might be slightly inaccurate but with some persistence you'll get there): during the Workers setup process, when you get prompted to "Enable Workflows" and you're bounced back over to your own fork of the GitHub repo, click Enable as instructed but don't go back yet. On the GitHub page, after clicking Enable, follow these steps:
1. Click "Deploy" on the left side menu.
2. You should see a workflow named "Deploy" on the main part of the screen. Trigger this to run this manually (I can't remember if it's 3-dot menu > run/trigger/etc) or if you click on the actual "Deploy" name and then trigger it on the following page, but something like that is what you want to do).
3. It took ~60 seconds to run. It turned green afterwards.
4. Only at this point did I return to the page where you finish deploying the Worker, and I proceeded by clicking the button as directed and this time it worked!

Now I'm struggling through the configuration (Failed resolving hostname <my domain>: No address associated with hostname) but at least I'm closer!

**Comment by morph2k** [comment]
> I had the same issues. I made multiple changes between attempts, one of them being the deployment of the test/Hello World worker, which did seem an essential one. In order to get things to reset I started over in an "incognito" window each time.
> 
> The other thing I did differently during my final/successful attempt, was manually trigger the "Deploy" action in GitHub. Going from memory (might be slightly inaccurate but with some persistence you'll get there): during the Workers setup process, when you get prompted to "Enable Workflows" and you're bounced back over to your own fork of the GitHub repo, click Enable as instructed but don't go back yet. On the GitHub page, after clicking Enable, follow these steps:
> 
>     1. Click "Deploy" on the left side menu.
> 
>     2. You should see a workflow named "Deploy" on the main part of the screen. Trigger this to run this manually (I can't remember if it's 3-dot menu > run/trigger/etc) or if you click on the actual "Deploy" name and then trigger it on the following page, but something like that is what you want to do).
> 
>     3. It took ~60 seconds to run. It turned green afterwards.
> 
>     4. Only at this point did I return to the page where you finish deploying the Worker, and I proceeded by clicking the button as directed and this time it worked!
> 
> 
> Now I'm struggling through the configuration (Failed resolving hostname : No address associated with hostname) but at least I'm closer!

Thank you! That seemed to do the trick! 
I believe that Deploy-action that had to be run manually in GitHub is what the last step of the "Click To Deploy" but for some reason it didn't do it properly.

**Comment by BombShellReaper** [comment]
> I had the same issues. I made multiple changes between attempts, one of them being the deployment of the test/Hello World worker, which did seem an essential one. In order to get things to reset I started over in an "incognito" window each time.
> 
> The other thing I did differently during my final/successful attempt, was manually trigger the "Deploy" action in GitHub. Going from memory (might be slightly inaccurate but with some persistence you'll get there): during the Workers setup process, when you get prompted to "Enable Workflows" and you're bounced back over to your own fork of the GitHub repo, click Enable as instructed but don't go back yet. On the GitHub page, after clicking Enable, follow these steps:
> 
> 1. Click "Deploy" on the left side menu.
> 2. You should see a workflow named "Deploy" on the main part of the screen. Trigger this to run this manually (I can't remember if it's 3-dot menu > run/trigger/etc) or if you click on the actual "Deploy" name and then trigger it on the following page, but something like that is what you want to do).
> 3. It took ~60 seconds to run. It turned green afterwards.
> 4. Only at this point did I return to the page where you finish deploying the Worker, and I proceeded by clicking the button as directed and this time it worked!
> 
> Now I'm struggling through the configuration (Failed resolving hostname : No address associated with hostname) but at least I'm closer!

I had the same issue and found the same problem. To be honest I gave up and used NameCheap for my DDNS needs. The controller has the built in option and it's super easy. I would still love to know how this works.
